# port
server:
  port: 8089

# H2 config
spring:
  datasource:
    url: jdbc:h2:file:./data/coindesk
    username: demouser
    password: 12345
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2
      settings.trace: false
      settings.web-allow-others: false
